spring:
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true 
  datasource:
    url: jdbc:h2:mem:testdb # URL para o banco de dados em memória
    username: sa  # Usuário padrão do H2
    password:  # Senha (vazia por padrão)
    driverClassName: org.h2.Driver
  
  mvc:
    async:
      request-timeout: 60000
    #pathmatch:
      #matching-strategy: ant_path_matcher
  #jackson:
    #default-property-inclusion: non_null
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true

security:
  allow-credentials: true
  allowed-public-apis:
    - /_ah/warmup
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
    - X-Frame-Options
  exposed-headers:
    - X-Xsrf-Tokens
    - X-Frame-Options
server:
  port: 8080
  error:
    include-message: always
logging:
  level:
    io:
      r2dbc:
        postgresql:
          QUERY: DEBUG
          PARAM: DEBUG
